import "./globals.css";
import Modal from "@/components/Modal";

export const metadata = {
  title: "Brello",
  description: "Generated by NK",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#FFFDFC]">
        {children}
        <Modal />
      </body>
    </html>
  );
}
